// Existing Playwright + real Edge; only local fixture URLs and synthetic files.
const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const path = require("node:path");
const crypto = require("node:crypto");
if (process.argv.includes("--help")) {
  console.log("PLAYWRIGHT_MODULE=<existing module> URL=http://127.0.0.1:8791/ OUTPUT_DIR=<scratch directory> node tests/browser_consumer.cjs");
  process.exit(0);
}
if (!process.env.PLAYWRIGHT_MODULE || !process.env.OUTPUT_DIR) throw new Error("Set PLAYWRIGHT_MODULE and OUTPUT_DIR; no dependencies are installed by this script.");
const { chromium } = require(process.env.PLAYWRIGHT_MODULE);
const url = process.env.URL || "http://127.0.0.1:8791/";
if (!['127.0.0.1', 'localhost'].includes(new URL(url).hostname)) throw new Error("Use a local fixture URL.");
const root = path.resolve(__dirname, "..");
const output = path.resolve(process.env.OUTPUT_DIR);
const checks = [];
const errors = [];
const dialogs = [];
let browser;
const file = (name, raw) => ({ name, mimeType: "application/json", buffer: Buffer.from(raw, "utf8") });
async function saveDownload(page, name) {
  const pending = page.waitForEvent("download");
  await page.locator("#download-report").focus();
  await page.keyboard.press("Enter");
  const download = await pending;
  const filename = path.join(output, name);
  await download.saveAs(filename);
  return JSON.parse(await fs.readFile(filename, "utf8"));
}
(async () => {
  await fs.mkdir(output, { recursive: true });
  browser = await chromium.launch({ channel: "msedge", headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const page = await context.newPage();
  page.setDefaultTimeout(10000);
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("dialog", async (dialog) => { dialogs.push(dialog.type()); await dialog.dismiss(); });
  const requested = [];
  page.on("request", (request) => requested.push(request.url()));
  await page.goto(url);
  const cases = JSON.parse(await fs.readFile(path.join(root, "tests/fixtures/review-cases.json"), "utf8"));
  for (const name of ["valid", "nan", "infinity", "empty", "duplicate", "count_missing", "invalid_interval", "drift", "ai_duration_warning", "malformed_json"]) {
    const item = cases.find((candidate) => candidate.name === name);
    await page.locator("#live-file").setInputFiles(file("live.json", item.live_json));
    await page.locator("#source-file").setInputFiles(file("source.json", item.source_json));
    await page.locator("#plan-file").setInputFiles(item.plan_json ? file("plan.json", item.plan_json) : []);
    assert.equal(await page.locator("#download-report").isDisabled(), true);
    const responsePromise = page.waitForResponse((response) => new URL(response.url()).pathname === "/api/review");
    await page.locator("#review-button").click();
    const response = await responsePromise;
    assert.equal(response.status(), 200);
    const report = await response.json();
    await page.locator("#status").getByText("رمز CLI: " + item.exit_code, { exact: false }).waitFor();
    assert.equal(report.exit_code, item.exit_code);
    assert.equal(report.submit_authorized, false);
    assert.equal(report.files.live.raw_sha256, crypto.createHash("sha256").update(item.live_json, "utf8").digest("hex"));
    assert.equal(await page.locator("#segment-rows tr").count(), report.rows.length);
    if (item.row_state) assert.ok(await page.locator(`#segment-rows tr[data-state="${item.row_state}"]`).count() > 0);
    if (item.reason) assert.ok((await page.locator("#blocking").textContent()).includes(item.reason));
    if (item.warning) assert.ok((await page.locator("#warnings").textContent()).includes(item.warning));
    if (["valid", "nan", "malformed_json"].includes(name)) assert.deepEqual(await saveDownload(page, name + "-review.json"), report);
    checks.push("real file selection -> Python HTTP review -> table: " + name);
  }
  const windows = await fs.readFile(path.join(root, "tests/fixtures/windows-snapshot.json"));
  await page.locator("#live-file").setInputFiles({ name: "windows.json", mimeType: "application/json", buffer: windows });
  await page.locator("#source-file").setInputFiles(path.join(root, "tests/fixtures/linux-snapshot.json"));
  await page.locator("#plan-file").setInputFiles([]);
  const bomResponse = page.waitForResponse((response) => new URL(response.url()).pathname === "/api/review");
  await page.locator("#review-button").click();
  const bomReport = await (await bomResponse).json();
  await page.locator("#status").getByText("رمز CLI: 0", { exact: false }).waitFor();
  assert.equal(bomReport.files.live.utf8_bom, true);
  assert.equal(bomReport.files.live.raw_sha256, crypto.createHash("sha256").update(windows).digest("hex"));
  checks.push("real UTF-8 BOM upload preserves original bytes and Python format adapter");
  const xss = JSON.stringify([{ segment_index: 1, start_sec: 0, end_sec: 4, current_label: "<img src=x onerror=alert(1)> مثال" }]);
  await page.locator("#live-file").setInputFiles(file("live.json", xss));
  await page.locator("#source-file").setInputFiles(file("source.json", xss));
  await page.locator("#review-button").click();
  await page.locator("#status").getByText("رمز CLI: 0", { exact: false }).waitFor();
  assert.equal(await page.locator("#segment-rows img").count(), 0);
  assert.ok((await page.locator("#segment-rows").textContent()).includes("<img src=x"));
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.setViewportSize({ width: 1280, height: 900 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  checks.push("labels remain text; keyboard download; phone390 and desktop have no page overflow");
  await page.locator("#tolerance").fill("0.2");
  assert.equal(await page.locator("#download-report").isDisabled(), true);
  assert.equal(await page.locator("#review-result").isHidden(), true);
  checks.push("changing an input invalidates the prior report and download");
  await page.locator("#live-file").setInputFiles(file("oversize.json", " ".repeat(256 * 1024 + 1)));
  await page.locator("#review-button").click();
  await page.locator("#status").getByText(/256 KiB/).waitFor();
  assert.equal(await page.locator("#download-report").isDisabled(), true);
  checks.push("oversize selected file fails visibly without retaining a prior success");
  assert.deepEqual(errors, []);
  assert.deepEqual(dialogs, []);
  assert.ok(requested.every((request) => new URL(request).origin === new URL(url).origin));
  const sourceFiles = {};
  for (const name of ["atlas_annotation/review.py", "atlas_annotation/web.py", "atlas_annotation/cli.py", "atlas_annotation/ui/index.html", "atlas_annotation/ui/app.js", "atlas_annotation/ui/style.css"]) sourceFiles[name] = crypto.createHash("sha256").update(await fs.readFile(path.join(root, name))).digest("hex");
  await fs.writeFile(path.join(output, "atlas-review-browser-result.json"), JSON.stringify({ checked_at: new Date().toISOString(), status: "passed", real_browser: "Microsoft Edge headless", source_sha: process.env.SOURCE_SHA || null, source_files_sha256: sourceFiles, checks, page_errors: errors, dialogs }, null, 2) + "\n");
  console.log("PASS: " + checks.length + " real Edge groups; " + output);
})().catch((error) => { console.error(error); process.exitCode = 1; }).finally(async () => { await browser?.close(); });
